CREATE TABLE landing_area.game_summaries (
    game_id BIGINT PRIMARY KEY,
    game_type CHAR(10),
    game_double_header CHAR(10),
    game_identifier VARCHAR(255),
    game_day_type CHAR(10),
    game_tiebreaker CHAR(10),
    game_number INT,
    game_calendar_event_id VARCHAR(255),
    game_season VARCHAR(4),
    date_time TIMESTAMP WITH TIME ZONE,
    original_date DATE,
    official_date DATE,
    day_night VARCHAR(10),
    time_str VARCHAR(5),
    ampm CHAR(2),
    coded_game_state CHAR(10),
    status_code CHAR(10),
    away_team_name VARCHAR(255),
    away_team_id INT,
    away_team_abbreviation VARCHAR(10),
    away_team_games_played INT,
    away_team_record_wins INT,
    away_team_record_losses INT ,
    home_team_name VARCHAR(255),
    home_team_id INT,
    home_team_abbreviation VARCHAR(10),
    home_team_games_played INT,
    home_team_record_wins INT,
    home_team_record_losses INT,
    venue_id INT,
    venue_name VARCHAR(255),
    venue_link VARCHAR(255),
    venue_capacity INT,
    venue_turf_type VARCHAR(50),
    venue_roof_type VARCHAR(50),
    venue_left_line INT,
    venue_left_center INT ,
    venue_center INT,
    venue_right_center INT ,
    venue_right_line INT,
    weather_condition VARCHAR(50),
    weather_temp VARCHAR(50),
    weather_wind VARCHAR(50),
    game_attendance INT,
    game_first_pitch TIMESTAMP WITH TIME ZONE,
    game_duration_minutes INT,
    -- UNIQUE (game_id, home_team_id, away_team_id, official_date)
);
