CREATE TABLE landing_area.game_day_player_season_stats_batting_performance (
  game_day_player_season_stats_batting_performance_sk SERIAL PRIMARY KEY,
  game_id INT,
  team_id INT,
  player_id INT,
  games_played INT,
  fly_outs INT,
  ground_outs INT,
  runs INT,
  doubles INT,
  triples INT,
  home_runs INT,
  strike_outs INT,
  base_on_balls INT,
  intentional_walks INT,
  hits INT,
  hit_by_pitch INT,
  avg DECIMAL,
  at_bats INT,
  obp DECIMAL,
  slg DECIMAL,
  ops DECIMAL,
  caught_stealing INT,
  stolen_bases INT,
  stolen_base_percentage DECIMAL,
  ground_into_double_play INT,
  ground_into_triple_play INT,
  plate_appearances INT,
  total_bases INT,
  rbi INT,
  left_on_base INT,
  sac_bunts INT,
  sac_flies INT,
  babip DECIMAL,
  catchers_interference INT,
  pickoffs INT,
  at_bats_per_home_run DECIMAL,
  UNIQUE (game_id, team_id, player_id) -- Ensuring each player's entry is unique per game and team
);
