CREATE TABLE landing_area.player_game_batting_performance (
  player_game_batting_performance_sk SERIAL PRIMARY KEY,
  game_id INT,
  team_id INT,
  player_id INT,
  summary VARCHAR(500),
  games_played INT,
  fly_outs INT,
  ground_outs INT,
  runs INT,
  doubles INT,
  triples INT,
  home_runs INT,
  strike_outs INT,
  base_on_balls INT,
  intentional_walks INT,
  hits INT,
  hit_by_pitch INT,
  at_bats INT,
  caught_stealing INT,
  stolen_bases INT,
  stolen_base_percentage DECIMAL, -- Assuming it's a percentage, might be NULL
  ground_into_double_play INT,
  ground_into_triple_play INT,
  plate_appearances INT,
  total_bases INT,
  rbi INT,
  left_on_base INT,
  sac_bunts INT,
  sac_flies INT,
  catchers_interference INT,
  pickoffs INT,
  at_bats_per_home_run DECIMAL, -- Assuming it's a ratio, might be NULL
  UNIQUE (game_id, team_id, player_id) -- Ensuring one entry per team per game per player
);
