CREATE TABLE landing_area.play_outcome (
    play_outcome_sk SERIAL PRIMARY KEY,
    game_id INT,
    at_bat_index INT,
    result_type VARCHAR(50),
    result_event VARCHAR(100),
    event_type VARCHAR(100),
    batter_player_id INT,
    batter_player_full_name VARCHAR(255),
    batSide CHAR(1),
    pitcher_player_id INT,
    pitcher_player_full_name VARCHAR(255),
    pitch_hand CHAR(1),
    splits_batter VARCHAR(50),
    splits_pitcher VARCHAR(50),
    splits_men_on_base VARCHAR(50),
    result_description TEXT,
    rbi INT,
    away_score INT,
    home_score INT,
    is_out BOOLEAN,
    balls INT,
    strikes INT,
    outs INT,
    half_inning VARCHAR(10),
    is_top_inning BOOLEAN,
    inning INT,
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    is_complete BOOLEAN,
    is_scoring_play BOOLEAN,
    has_review BOOLEAN,
    has_out BOOLEAN,
    captivating_index INT,
    home_team_win_probability FLOAT,
    away_team_win_probability FLOAT,
    home_team_win_probability_added FLOAT
);
