CREATE TABLE landing_area.teams (
  teams_sk SERIAL PRIMARY KEY,
  team_id INT,
  team_full_name VARCHAR(255),
  team_link VARCHAR(255),
  team_season VARCHAR(4),
  venue_id INT,
  venue_name VARCHAR(255),
  venue_link VARCHAR(255),
  team_code VARCHAR(10),
  file_code VARCHAR(10),
  abbreviation VARCHAR(10),
  team_name VARCHAR(255),
  first_year_of_play VARCHAR(4),
  league_id INT,
  league_name VARCHAR(255),
  league_link VARCHAR(255),
  division_id INT,
  division_name VARCHAR(255),
  division_link VARCHAR(255),
  sport_id INT,
  sport_name VARCHAR(255),
  sport_link VARCHAR(255),
  short_name VARCHAR(255),
  parent_org_name VARCHAR(255),
  parent_org_id INT,
  franchise_name VARCHAR(255),
  club_name VARCHAR(255),
  active BOOLEAN,
  UNIQUE (team_id, team_full_name, team_season) 
);
